import { getNav, buildPage } from "./shared.js";

export function renderMines() {
  var nav = getNav("mines");
  var gridHtml = "";
  for (var i = 0; i < 25; i++) {
    gridHtml += '<div id="mt' + i + '" style="aspect-ratio:1;background:#1a1a1a;border-radius:6px;display:flex;align-items:center;justify-content:center;border:1px solid #333;cursor:pointer"><div style="width:14px;height:14px;background:#444;border-radius:50%"></div></div>';
  }
  var html = '<div class="head"><div class="logo" style="color:#ffcc00;text-shadow:0 0 20px #ffcc00">⚡ L.F.K PREDICTOR ⚡</div><div class="tag" style="color:#ff3333">SPORTYBET MINES SIGNAL</div></div>';
  html += '<div class="card glow"><h3 class="ct" style="color:#ffcc00">⚡ 5x5 MINE GRID ⚡</h3><div id="mg" style="display:grid;grid-template-columns:repeat(5,1fr);gap:6px;background:#000;padding:15px;border-radius:10px;border:2px solid #ffcc00;margin-top:10px">' + gridHtml + '</div><p class="muted" style="margin-top:10px;text-align:center;color:#ffcc00" id="hint">Click ANALYZE - Green tiles = SAFE to click</p></div>';
  html += '<div class="card" style="border:1px solid #ffcc00"><label style="color:#ffcc00">SERVER SEED (from Provably Fair)</label><input id="ss" placeholder="Paste server seed" style="border:1px solid #ffcc00"></div>';
  html += '<div class="card" style="border:1px solid #ffcc00"><label style="color:#ffcc00">CLIENT SEED (from Provably Fair)</label><input id="cs" placeholder="Paste client seed" style="border:1px solid #ffcc00"></div>';
  html += '<div class="card" style="border:1px solid #ffcc00"><label style="color:#ffcc00">MINES (1-24)</label><input id="nm" type="number" min="1" max="24" value="3" style="border:1px solid #ffcc00"></div>';
  html += '<button class="btn" id="go" style="background:linear-gradient(135deg,#ffcc00,#ff8800);color:#000;box-shadow:0 0 30px #ffcc00">⚡ ANALYZE MINES ⚡</button>';
  html += '<div id="overlay" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.9);z-index:1000;justify-content:center;align-items:center;flex-direction:column;color:#ffcc00;font-size:20px;font-weight:900;letter-spacing:3px"><div style="font-size:40px;margin-bottom:20px">⚡</div><div>CALCULATING MINE POSITIONS...</div><div style="font-size:12px;margin-top:10px;color:#888">Using SHA512 + Stake.com algorithm</div></div>';
  html += '<div id="r" style="margin-top:15px"></div>';
  html += "<script>document.getElementById('go').addEventListener('click',async function(){var b=this;var ss=document.getElementById('ss').value.trim();var cs=document.getElementById('cs').value.trim();var nm=parseInt(document.getElementById('nm').value)||3;if(!ss||!cs){alert('Please enter both server seed and client seed');return}b.disabled=true;b.textContent='CALCULATING...';document.getElementById('overlay').style.display='flex';for(var i=0;i<25;i++){var t=document.getElementById('mt'+i);t.style.background='#1a1a1a';t.style.border='1px solid #333';t.innerHTML='<div style=\"width:14px;height:14px;background:#444;border-radius:50%\"></div>';t.classList.remove('safe','mine');}document.getElementById('r').innerHTML='';document.getElementById('hint').textContent='Analyzing...';var fd=new FormData();fd.append('server_seed',ss);fd.append('client_seed',cs);fd.append('num_mines',nm);try{var resp=await fetch('/api/mines',{method:'POST',body:fd});var d=await resp.json();if(d.ok&&d.grid&&d.minePositions){for(var i=0;i<25;i++){var t=document.getElementById('mt'+i);if(d.minePositions.indexOf(i)!==-1){t.style.background='#330000';t.style.border='2px solid #ff0000';t.innerHTML='<div style=\"width:12px;height:12px;background:#ff0000;border-radius:50%;box-shadow:0 0 8px #ff0000\"></div>';t.classList.add('mine');}else{t.style.background='#003300';t.style.border='2px solid #00ff66';t.innerHTML='<div style=\"width:16px;height:16px;background:#00ff66;border-radius:50%;box-shadow:0 0 12px #00ff66\"></div>';t.classList.add('safe');}}var html2='<div class=\"card glow\" style=\"border:2px solid #00ff66\"><h3 class=\"ct\" style=\"color:#00ff66\">⚡ '+d.confidence+'% CONFIDENCE</h3><p class=\"muted\" style=\"color:#00ff66;font-size:14px\">✅ GREEN tiles = SAFE to click</p><p class=\"muted\" style=\"color:#ff3333\">❌ RED tiles = DO NOT CLICK (mines)</p><p class=\"muted\" style=\"color:#ffcc00\">Mine positions: ['+d.minePositions.join(', ')+']</p><p class=\"muted\" style=\"color:#888;font-size:11px\">Hash: '+(d.hash||'computed')+'...</p><button class=\"btn\" onclick=\"location.reload()\">NEW GAME</button></div>';document.getElementById('r').innerHTML=html2;document.getElementById('hint').textContent='Green = SAFE | Red = MINES';}else{alert('Error: '+(d.error||'unknown'));}document.getElementById('overlay').style.display='none';b.disabled=false;b.textContent='⚡ ANALYZE MINES ⚡';}catch(e){alert('Error: '+e.message);document.getElementById('overlay').style.display='none';b.disabled=false;b.textContent='⚡ ANALYZE MINES ⚡';}});</script>";
  return buildPage("MINES", nav, html);
}
