export function getNav(active) {
  return '<div class="nav"><a href="/" class="' + (active === 'home' ? 'active' : '') + '"><span class="icon">⚡</span><span>HOME</span></a><a href="/mines" class="' + (active === 'mines' ? 'active' : '') + '"><span class="icon">💣</span><span>MINES</span></a></div>';
}

export const CSS = '*{box-sizing:border-box;margin:0;padding:0}:root{--yellow:#ffcc00;--orange:#ff8800;--red:#ff3333;--green:#00ff66;--black:#000;--card:#0a0a0a}body{font-family:"Courier New",monospace;background:#000;color:#fff;min-height:100vh;overflow-x:hidden;margin:0}canvas#m{position:fixed;top:0;left:0;width:100%;height:100%;z-index:0;opacity:.2}canvas#r{position:fixed;top:0;left:0;width:100%;height:100%;z-index:1;pointer-events:none}.lightning{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(255,204,0,.05);z-index:2;pointer-events:none;animation:flash 5s infinite}@keyframes flash{0%,80%,100%{opacity:0}82%{opacity:1;background:rgba(255,204,0,.4);box-shadow:inset 0 0 300px rgba(255,204,0,.6)}85%{opacity:0}87%{opacity:.8;background:rgba(255,51,51,.3);box-shadow:inset 0 0 200px rgba(255,51,51,.5)}90%{opacity:0}}.c{position:relative;z-index:3;max-width:560px;margin:0 auto;padding:12px;padding-bottom:80px}.nav{display:flex;gap:4px;margin-bottom:18px;background:rgba(0,0,0,.8);padding:5px;border-radius:10px;border:1px solid #ffcc00;position:sticky;top:8px;z-index:10}.nav a{flex:1;text-align:center;padding:10px;color:#888;text-decoration:none;font-size:9px;font-weight:700;border-radius:5px;display:flex;flex-direction:column;align-items:center;gap:3px}.nav a.active{background:rgba(255,204,0,.2);color:#ffcc00;box-shadow:0 0 10px #ffcc00}.head{text-align:center;padding:20px 0 12px;border-bottom:1px solid #ffcc00;margin-bottom:18px}.logo{font-size:22px;font-weight:900;color:#ffcc00;text-shadow:0 0 20px #ffcc00;letter-spacing:2px}.tag{font-size:9px;margin-top:5px;letter-spacing:2px}.card{background:linear-gradient(135deg,rgba(255,204,0,.05),#0a0a0a);border:1px solid #333;border-radius:12px;padding:16px;margin:10px 0;backdrop-filter:blur(5px)}.card.glow{box-shadow:0 0 30px rgba(255,204,0,.2);border-color:#ffcc00}.ct{color:#ffcc00;margin-bottom:10px;font-size:14px;letter-spacing:1px}.muted{color:#888;font-size:12px;margin:4px 0}label{display:block;color:#ffcc00;font-size:10px;font-weight:700;margin:12px 0 5px;letter-spacing:2px}input{width:100%;padding:11px;background:rgba(0,0,0,.7);color:#fff;border:1px solid #444;border-radius:8px;font-size:14px;font-family:inherit;box-sizing:border-box}input:focus{outline:none;border-color:#ffcc00}.btn{display:block;width:100%;padding:14px;background:linear-gradient(135deg,#ffcc00,#ff8800);color:#000;font-weight:900;font-size:13px;border:none;border-radius:8px;margin-top:14px;cursor:pointer;text-transform:uppercase;letter-spacing:2px;font-family:inherit;box-shadow:0 0 30px #ffcc00;text-align:center;text-decoration:none}.btn:disabled{opacity:.5;cursor:wait}';

export const EFFECTS_SCRIPT = '<canvas id="m"></canvas><canvas id="r"></canvas><div class="lightning"></div><script>var c=document.getElementById("m"),x=c.getContext("2d");var rain=document.getElementById("r"),rc=rain.getContext("2d");function size(){c.width=window.innerWidth;c.height=window.innerHeight;rain.width=window.innerWidth;rain.height=window.innerHeight}size();window.addEventListener("resize",size);var ch="01<>{}[]/\\\\$#@!%&*+=";var fs=16;var cols=Math.floor(c.width/fs);var drops=Array(cols).fill(1);setInterval(function(){x.fillStyle="rgba(0,0,0,0.05)";x.fillRect(0,0,c.width,c.height);x.fillStyle="#ffcc00";x.font=fs+"px monospace";for(var i=0;i<drops.length;i++){var t=ch[Math.floor(Math.random()*ch.length)];x.fillText(t,i*fs,drops[i]*fs);if(drops[i]*fs>c.height&&Math.random()>.975)drops[i]=0;drops[i]++}},33);var rlines=[];for(var i=0;i<15;i++){rlines.push({x:Math.random()*rain.width,len:Math.random()*30+10,speed:Math.random()*5+3})}setInterval(function(){rc.fillStyle="rgba(0,0,0,0.15)";rc.fillRect(0,0,rain.width,rain.height);rc.strokeStyle="rgba(255,204,0,0.4)";rc.lineWidth=1;for(var i=0;i<rlines.length;i++){var r=rlines[i];rc.beginPath();rc.moveTo(r.x,0);rc.lineTo(r.x,r.len);rc.stroke();r.x+=r.speed;if(r.x>rain.width)r.x=0}},50);</' + 'script>';

export function buildPage(title, nav, body) {
  return '<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + title + ' | L.F.K PREDICTOR</title><style>' + CSS + '</style></head><body>' + EFFECTS_SCRIPT + '<div class="c">' + nav + body + '</div></body></html>';
}
